# Generated by Django 4.2.6 on 2023-10-20 20:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stock", "0002_reactions"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Reactions",
            new_name="Reaction",
        ),
    ]
