# Generated by Django 4.2.6 on 2023-10-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="first_name",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="last_name",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
